### ISSUE TITLE
google.protobuf.text_format.ParseError: 2:1 : ';': Expected identifier or number, got ;.

### ISSUE THREAD

**Issue by pidugusundeep** [IntelAI/tools#4]
```
root@00000:/workspace/tensorflow# python tensorflow/python/tools/freeze_graph.py \
>      --input_graph /workspace/quantization/RL_S2S_1544356761_saved_model.pb \
>      --output_graph /workspace/quantization/freezed_graph.pb \
>      --input_binary False \
>      --input_checkpoint /workspace/quantization/model.checkpoint-27000.data-00000-of-00001 \
>      --output_node_names OUTPUT_NODE_NAMES
Traceback (most recent call last):
  File "tensorflow/python/tools/freeze_graph.py", line 491, in <module>
    run_main()
  File "tensorflow/python/tools/freeze_graph.py", line 488, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tensorflow/python/tools/freeze_graph.py", line 487, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "tensorflow/python/tools/freeze_graph.py", line 381, in main
    flags.saved_model_tags, checkpoint_version)
  File "tensorflow/python/tools/freeze_graph.py", line 340, in freeze_graph
    input_graph_def = _parse_input_graph_proto(input_graph, input_binary)
  File "tensorflow/python/tools/freeze_graph.py", line 253, in _parse_input_graph_proto
    text_format.Merge(f.read(), input_graph_def)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 574, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 631, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 654, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 676, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 744, in _MergeField
    name = tokenizer.ConsumeIdentifierOrNumber()
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 1212, in ConsumeIdentifierOrNumber
    raise self.ParseError('Expected identifier or number, got %s.' % result)
google.protobuf.text_format.ParseError: 2:1 : ';': Expected identifier or number, got ;.

```

How do i fix this ?

**Comment by wl4135** [comment]
I also encountered this problem, did you solve it?

**Comment by ftian1** [comment]
@wl4135 @pidugusundeep sorry for late response. could you pls share us the reproduce steps and related pb file? it's more like protobuf parse issue rather than quantization tool issue.
